name: Auto Update update.json

on:
  release:
    types: [published]  # Triggers when you publish a release

jobs:
  update-json:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # REQUIRED for pushing changes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main  # Change to 'master' if your default branch is master

      - name: Generate update.json
        run: |
          echo "Generating update.json..."
          cat <<EOF > update.json
          {
            "version": "${{ github.event.release.tag_name }}",
            "versionCode": 2,
            "zipUrl": "${{ github.event.release.assets[0].browser_download_url }}",
            "changelog": "${{ github.event.release.html_url }}"
          }
          EOF

      - name: Commit and Push update.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add update.json
          git commit -m "Auto-update update.json for ${{ github.event.release.tag_name }}" || echo "No changes to commit"
          git push origin main
